project:
  type: website
  output-dir: docs

website:
  description: "Toddling through AI and looking for the staircase"
  site-url: https://shaunhaney.github.io # you must change this appropriately for RSS feeds to work properly
  title: "FrogBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shaunhaney
format:
  html:
    title-block-banner: images/banner.jpg
    css:
      - frog.scss
      - styles.css


